version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=api_for_library_db
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=library_user
  web:
    build: .
    command: uvicorn library.main:app --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db