"""Add ondelete SET NULL to author_id in Books

Revision ID: 0c57300b9155
Revises: 12a4380437e0
Create Date: 2024-12-11 08:50:30.343227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c57300b9155'
down_revision: Union[str, None] = '12a4380437e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
