"""Initial migration

Revision ID: 7c0860c40083
Revises: 
Create Date: 2024-12-11 05:30:34.719011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0860c40083'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Authors_last_name', table_name='Authors')
    op.create_index(op.f('ix_Authors_last_name'), 'Authors', ['last_name'], unique=False)
    op.drop_constraint('Books_author_id_fkey', 'Books', type_='foreignkey')
    op.create_foreign_key(None, 'Books', 'Authors', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('Borrow', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('Borrow_book_id_fkey', 'Borrow', type_='foreignkey')
    op.create_foreign_key(None, 'Borrow', 'Books', ['book_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Borrow', type_='foreignkey')
    op.create_foreign_key('Borrow_book_id_fkey', 'Borrow', 'Books', ['book_id'], ['id'])
    op.alter_column('Borrow', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'Books', type_='foreignkey')
    op.create_foreign_key('Books_author_id_fkey', 'Books', 'Authors', ['author_id'], ['id'])
    op.drop_index(op.f('ix_Authors_last_name'), table_name='Authors')
    op.create_index('ix_Authors_last_name', 'Authors', ['last_name'], unique=True)
    # ### end Alembic commands ###
